Organizations:
- &id006
  Name: OrdererOrg
  ID: OrdererMSP
  MSPDir: ../organizations/ordererOrganizations/example.com/msp
  Policies:
    Readers:
      Type: Signature
      Rule: OR('OrdererMSP.member')
    Writers:
      Type: Signature
      Rule: OR('OrdererMSP.member')
    Admins:
      Type: Signature
      Rule: OR('OrdererMSP.admin')
    Endorsement:
      Type: Signature
      Rule: OR('OrdererMSP.member')
  OrdererEndpoints:
  - orderer:7050
- &id008
  Name: Org1MSP
  ID: Org1MSP
  MSPDir: ../organizations/peerOrganizations/org1.example.com/msp
  Policies:
    Readers:
      Type: Signature
      Rule: OR('Org1MSP.member')
    Writers:
      Type: Signature
      Rule: OR('Org1MSP.member')
    Admins:
      Type: Signature
      Rule: OR('Org1MSP.admin')
    Endorsement:
      Type: Signature
      Rule: OR('Org1MSP.peer')
  AnchorPeers:
  - Host: peer0-org1
    Port: 7051
- Name: EliteMSP
  ID: EliteMSP
  MSPDir: ../organizations/peerOrganizations/elite.example.com/msp
  Policies:
    Readers:
      Type: Signature
      Rule: OR('EliteMSP.member')
    Writers:
      Type: Signature
      Rule: OR('EliteMSP.member')
    Admins:
      Type: Signature
      Rule: OR('EliteMSP.admin')
    Endorsement:
      Type: Signature
      Rule: OR('EliteMSP.peer')
  AnchorPeers:
  - Host: peer0-elite
    Port: 9051
Capabilities:
  Channel:
    V2_0: true
  Orderer:
    V2_0: true
  Application:
    V2_0: true
Application:
  ACLs: &id009
    lscc/ChaincodeExists: /Channel/Application/Readers
    lscc/GetDeploymentSpec: /Channel/Application/Readers
    lscc/GetChaincodeData: /Channel/Application/Readers
    lscc/GetInstantiatedChaincodes: /Channel/Application/Readers
    qscc/GetChainInfo: /Channel/Application/Readers
    qscc/GetBlockByNumber: /Channel/Application/Readers
    qscc/GetBlockByHash: /Channel/Application/Readers
    qscc/GetTransactionByID: /Channel/Application/Readers
    qscc/GetBlockByTxID: /Channel/Application/Readers
    cscc/GetConfigBlock: /Channel/Application/Readers
    cscc/GetConfigTree: /Channel/Application/Readers
    cscc/SimulateConfigTreeUpdate: /Channel/Application/Readers
    peer/Propose: /Channel/Application/Writers\
    peer/ChaincodeToChaincode: /Channel/Application/Readers
    event/Block: /Channel/Application/Readers
    event/FilteredBlock: /Channel/Application/Readers
    _lifecycle/CheckCommitReadiness: /Channel/Application/Writers
    _lifecycle/CommitChaincodeDefinition: /Channel/Application/Writers
    _lifecycle/QueryChaincodeDefinition: /Channel/Application/Readers
  Organizations: null
  Policies: &id010
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: MAJORITY Endorsement
    Endorsement:
      Type: ImplicitMeta
      Rule: MAJORITY Endorsement
  Capabilities:
    V2_0: true
Orderer:
  OrdererType: etcdraft
  Addresses: &id003
  - orderer:7050
  - orderer2:7050
  - orderer3:7050
  - orderer4:7050
  - orderer5:7050
  EtcdRaft: &id004
    Consenters:
    - Host: orderer
      Port: 7050
      ClientTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
      ServerTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
    - Host: orderer2
      Port: 7050
      ClientTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/server.crt
      ServerTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/server.crt
    - Host: orderer3
      Port: 7050
      ClientTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/server.crt
      ServerTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/server.crt
    - Host: orderer4
      Port: 7050
      ClientTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer4.example.com/tls/server.crt
      ServerTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer4.example.com/tls/server.crt
    - Host: orderer5
      Port: 7050
      ClientTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer5.example.com/tls/server.crt
      ServerTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer5.example.com/tls/server.crt
  BatchTimeout: 2s
  BatchSize: &id005
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations: null
  Policies: &id007
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
    BlockValidation:
      Type: ImplicitMeta
      Rule: ANY Writers
Channel:
  Policies: &id001
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
  Capabilities: &id002
    V2_0: true
Profiles:
  TwoOrgsOrdererGenesis:
    Policies: *id001
    Capabilities: *id002
    Orderer:
      OrdererType: etcdraft
      Addresses: *id003
      EtcdRaft: *id004
      BatchTimeout: 2s
      BatchSize: *id005
      Organizations:
      - *id006
      Policies: *id007
      Capabilities:
        V2_0: true
    Consortiums:
      SampleConsortium:
        Organizations:
        - *id008
        - Elite
  TwoOrgsChannel:
    Policies: *id001
    Capabilities: *id002
    Consortium: SampleConsortium
    Application:
      ACLs: *id009
      Organizations:
      - *id008
      - Elite
      Policies: *id010
      Capabilities:
        V2_0: true
